name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Filter formulas for recipes
        id: filter-formulas
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          MATCHED_FILES=$(echo "$CHANGED_FILES" | grep -E '\-recipes\.rb$' || true)
          if [ -z "$MATCHED_FILES" ]; then
            echo "No matching formulas found."
            exit 0
          fi
          echo "MATCHED_FILES=$MATCHED_FILES" >> $GITHUB_ENV

      - run: brew test-bot --only-formulae $MATCHED_FILES
        if: github.event_name == 'pull_request' && env.MATCHED_FILES != ''

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request' && env.MATCHED_FILES != ''
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'

      #- name: Setup tmate session
      #  if: success() || failure()
      #  uses: mxschmitt/action-tmate@v3
